apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: shod4n/mgdockertest
